package: global_settings
version: '2.2.0-dev'
author: 'RexDude, Sysix, Markus Staab, Jan Kristinus'
supportpage: http://www.redaxo.org/de/forum/
page:
    title: translate:title
    perm: global_settings[settings] 
    pjax: false
    icon: rex-icon fa-wrench
    subpages:
        settings: { title: 'translate:settings', perm: global_settings[settings] }
        fields: { title: 'translate:fields', perm: admin[] }
        help:
            title: 'translate:help'
            perm: admin[]
            subpages:
                help:  
                     { title: 'translate:quicknavi_help',  icon: rex-icon fa-question-circle, subPath: README.md} 
                changelog: { title: 'translate:help_changelog' }
                license: { title: 'translate:help_license' }
requires:
    redaxo: '^5.0'

